"""Source definitions for generated V2 modeling schemas.

Edit this catalog, then run tools/build_contract_schemas.py. Generated standalone
schemas are distribution artifacts; CI --check must detect drift.
"""
from __future__ import annotations

TEXT = {"type": "string", "minLength": 1, "pattern": r"\S"}
ID = {"type": "string", "pattern": r"^[A-Za-z][A-Za-z0-9_.-]{0,95}$"}
PATH = {"type": "string", "minLength": 1, "pattern": r"^(?![/\\])(?!.*(?:^|[/\\])\.\.(?:[/\\]|$))(?!.*:).+$"}
HASH = {"type": "string", "pattern": "^[a-f0-9]{64}$"}
TIME = {"type": "string", "format": "date-time"}
NUMBER = {"type": "number"}
BOOL = {"type": "boolean"}


def obj(fields, optional=()):
    return {"type": "object", "additionalProperties": False,
            "required": [k for k in fields if k not in optional], "properties": fields}


def arr(item, minimum=0, unique=False):
    return {"type": "array", "items": item, "minItems": minimum, "uniqueItems": unique}


def enum(*values):
    return {"enum": list(values)}


def nullable(value):
    return {"anyOf": [value, {"type": "null"}]}


def mapping(item):
    return {"type": "object", "additionalProperties": item}


def contract(fields, optional=()):
    return obj({"schema_version": {"const": "2.0"}, **fields}, optional=optional)


LIMITS = obj({"timeout_seconds": {"type": "number", "exclusiveMinimum": 0},
              "memory_mb": nullable({"type": "integer", "minimum": 1})})
SOURCE = obj({"uri": TEXT, "accessed_at": TIME, "license": TEXT})
DEPENDENCY = obj({"artifact_id": ID, "sha256": HASH})
ARTIFACT = obj({"artifact_id": ID, "path": PATH, "sha256": HASH,
    "size_bytes": {"type": "integer", "minimum": 0}, "created_at": TIME,
    "producer": ID, "depends_on": arr(DEPENDENCY),
    "status": enum("DRAFT", "VALID", "FROZEN", "STALE", "FAILED")})
TASK_TYPE = enum("regression", "optimization", "time_series", "mechanism", "simulation",
                 "graph", "classification", "decision")
OUTPUT = obj({"name": ID, "path": PATH, "format": enum("json", "csv", "xlsx", "txt"),
              "fields": arr(obj({"name": TEXT, "type": enum("number", "integer", "string", "boolean"),
                                  "unit": TEXT}), 1), "precision": {"type": "integer", "minimum": 0, "maximum": 16}})
TRIGGER = obj({"metric": TEXT, "operator": enum("gt", "ge", "lt", "le", "eq"), "threshold": NUMBER})
CONSTRAINT = obj({"constraint_id": ID, "expression": TEXT, "unit": TEXT,
                  "source_ref": TEXT, "validator": ID, "tolerance": {"type": "number", "minimum": 0}})


def catalog():
    return {
        "input_manifest": contract({"case_id": ID, "created_at": TIME, "producer": ID,
            "frozen": {"const": True}, "files": arr(obj({
                "input_id": ID, "path": PATH, "role": enum("problem", "data", "template", "rule", "description"),
                "sha256": HASH, "size_bytes": {"type": "integer", "minimum": 1},
                "source": SOURCE, "readonly": {"const": True}}), 1)}),
        "problem_frame": contract({"case_id": ID, "producer": ID, "source_refs": arr(ID, 1, True),
            "data_audit_ref": ID, "questions": arr(obj({"question_id": ID, "title": TEXT,
                "task_type": TASK_TYPE, "inputs": arr(ID, 1, True), "outputs": arr(OUTPUT, 1),
                "objective": obj({"description": TEXT, "metric": TEXT, "sense": enum("min", "max", "match", "explain")}),
                "constraints": arr(CONSTRAINT), "source_refs": arr(TEXT, 1, True),
                "resources": LIMITS}), 1)}),
        "problem_dag": contract({"nodes": arr(obj({"question_id": ID, "depends_on": arr(ID, 0, True)}), 1)}),
        "ambiguity_register": contract({"reviewed_by": ID, "reviewed_at": TIME,
            "items": arr(obj({"ambiguity_id": ID, "severity": enum("low", "medium", "high"),
                "source": TEXT, "issue": TEXT, "interpretations": arr(TEXT, 2),
                "question_ids": arr(ID, 1, True), "status": enum("unresolved", "resolved", "mitigated"),
                "resolution": nullable(TEXT), "evidence_refs": arr(TEXT)}))}),
        "assumption_ledger": contract({"entry_id": ID, "assumption_id": ID, "supersedes": nullable(ID),
            "content": TEXT, "kind": enum("necessary", "simplifying"), "source_refs": arr(TEXT, 1, True),
            "question_ids": arr(ID, 1, True), "formula_ids": arr(ID, 0, True), "validation_method": TEXT,
            "sensitivity_status": enum("pending", "tested", "not_applicable"),
            "status": enum("pending", "accepted", "rejected"), "created_at": TIME, "producer": ID}),
        "symbol_table": contract({"symbols": arr(obj({"symbol_id": ID, "symbol": TEXT,
            "meaning": TEXT, "unit": TEXT, "dimensions": mapping({"type": "integer"}), "code_name": ID,
            "domain": obj({"kind": enum("real", "integer", "boolean"), "lower": nullable(NUMBER), "upper": nullable(NUMBER)}),
            "question_ids": arr(ID, 1, True)}), 1)}),
        "method_card": contract({"question_id": ID, "methods": arr(obj({"method_id": ID,
            "role": enum("main_candidate", "usable_baseline", "conditional_fallback", "diagnostic_reference"),
            "idea": TEXT, "completes_task": BOOL, "outputs": arr(TEXT, 1, True),
            "assumption_ids": arr(ID, 0, True), "source_refs": arr(TEXT, 1, True),
            "cost": LIMITS, "fallback_trigger": nullable(TRIGGER), "validation_plan": arr(TEXT, 1),
            "rejection_reason": nullable(TEXT)}), 2),
            "critic": obj({"actor_id": ID, "findings": arr(TEXT), "evidence_refs": arr(TEXT, 1)})}),
        "risk_probe": contract({"question_id": ID, "method_id": ID, "run_id": ID,
            "checks": arr(obj({"category": enum("executability", "coverage", "assumptions", "degeneracy", "perturbation", "scale"),
                "status": enum("PASS", "CONDITIONAL", "FAIL", "NOT_APPLICABLE"),
                "evidence_refs": arr(TEXT, 1), "metrics": mapping(NUMBER), "thresholds": mapping(NUMBER), "reason": TEXT}), 6),
            "verdict": enum("PASS", "CONDITIONAL", "FAIL")}),
        "method_decision": contract({"decision_id": ID, "question_id": ID, "main_method_id": ID,
            "baseline_method_id": ID, "rationale": TEXT, "evidence_refs": arr(ID, 1, True),
            "decided_by": enum("agent", "human"), "actor_id": ID, "decided_at": TIME,
            "human_event_id": nullable(ID), "execution_role": enum("main", "fallback")}, optional=("execution_role",)),
        "model_spec": contract({"question_id": ID, "method_id": ID, "decision_id": ID,
            "actor_id": ID, "task_type": TASK_TYPE, "variables": arr(ID, 1, True),
            "formulae": arr(obj({"formula_id": ID, "expression": TEXT,
                "input_symbols": arr(ID, 0, True), "output_symbol": ID, "unit_check": TEXT}), 1),
            "objective": obj({"metric": TEXT, "sense": enum("min", "max", "match", "explain"), "expression": TEXT}),
            "constraints": arr(CONSTRAINT), "parameters": mapping(NUMBER), "inputs": arr(ID, 1, True),
            "outputs": arr(OUTPUT, 1), "seed": {"type": "integer", "minimum": 0, "maximum": 4294967295},
            "validation_plan": obj({"checks": arr(ID, 1, True), "independent_entrypoint": PATH,
                "criteria": obj({"path": PATH, "sha256": HASH}),
                "probe": obj({"path": PATH, "sha256": HASH}),
                "screening_card": obj({"path": PATH, "sha256": HASH})}, optional=("criteria", "probe", "screening_card")),
            "implementation": obj({"entrypoint": PATH, "code_files": arr(PATH, 1, True), "language": {"const": "python"}}),
            "upstream_freezes": arr(obj({"question_id": ID, "freeze_id": ID}), 0, True),
            "fallback_authorization": obj({"card": obj({"path": PATH, "sha256": HASH}),
                "probe_report": obj({"path": PATH, "sha256": HASH}), "probe_run": obj({"path": PATH, "sha256": HASH})}),
            "data_split": obj({"strategy": enum("none", "holdout", "time", "group", "rolling"),
                "train_ids": arr(TEXT, 0, True), "test_ids": arr(TEXT, 0, True), "fit_ids": arr(TEXT, 0, True),
                "target": nullable(TEXT), "features": arr(TEXT, 0, True),
                "sample_times": mapping(TIME), "sample_groups": mapping(TEXT)}), "limits": LIMITS}, optional=("upstream_freezes", "fallback_authorization")),
        "workflow_state": contract({"case_id": ID, "revision": {"type": "integer", "minimum": 0},
            "created_at": TIME, "updated_at": TIME, "workspace_kind": enum("competition", "fixture"),
            "interaction_mode": enum("autopilot", "human_gate"), "rigor_profile": enum("lean", "submission"),
            "blind_reference_mode": BOOL, "artifacts": arr(ARTIFACT),
            "gates": arr(obj({"gate_id": enum("G0", "G1", "G2", "G3", "G3.5", "G4", "G5", "G6", "G7", "G8"),
                "status": enum("NOT_RUN", "PASS", "WARN", "FAIL", "BLOCKED"), "artifact_refs": arr(ID),
                "checked_at": TIME, "blockers": arr(TEXT)})),
            "retry_history": arr(obj({"cause_id": ID, "category": enum("ENV_FAILURE", "DATA_FAILURE", "CODE_FAILURE", "MODEL_FAILURE", "VALIDATION_FAILURE", "POLICY_FAILURE"),
                "attempt": {"type": "integer", "minimum": 1, "maximum": 3}, "question_id": ID,
                "message": TEXT, "changed_artifacts": arr(ID), "at": TIME})),
            "reference_access": arr(obj({"source": TEXT, "question_id": ID, "same_problem": BOOL,
                                         "at": TIME, "baseline_freeze_id": nullable(ID),
                                         "blind_reference_mode": BOOL}, optional=("blind_reference_mode",)))}),
        "ai_usage": contract({"event_id": ID, "timestamp": TIME, "provider": TEXT, "model": TEXT,
            "version_date": nullable(TEXT), "question_id": nullable(ID),
            "activity": enum("literature", "problem_analysis", "modeling", "coding", "visualization", "writing", "review"),
            "input_scope": arr(TEXT, 1), "output_used": BOOL, "human_postprocess": nullable(TEXT),
            "artifact_refs": arr(ID), "actor_id": ID}),
        "run_manifest": contract({"run_id": ID, "question_id": ID, "method_id": ID,
            "role": enum("main", "baseline", "probe", "validator", "fallback"), "producer": {"const": "runner"},
            "actor_id": ID, "backend": TEXT,
            "capabilities": obj({"os_sandbox": BOOL, "network_isolation": BOOL,
                "filesystem_isolation": BOOL, "memory_limit": BOOL, "cpu_limit": BOOL,
                "timeout": BOOL, "process_tree_termination": enum("best_effort", "enforced", "unsupported")}),
            "interpreter": obj({"requested": TEXT, "executable": TEXT, "sha256": HASH,
                "version": TEXT, "platform": TEXT, "packages": mapping(TEXT)}),
            "argv": arr(TEXT, 1), "cwd": TEXT, "environment": mapping(TEXT),
            "seed": {"type": "integer", "minimum": 0, "maximum": 4294967295},
            "started_at": TIME, "ended_at": TIME, "duration_seconds": {"type": "number", "minimum": 0},
            "timeout_seconds": {"type": "number", "exclusiveMinimum": 0},
            "returncode": nullable({"type": "integer"}), "timed_out": BOOL,
            "status": enum("PASS", "FAIL"), "failure_class": nullable(enum("ENV_FAILURE", "DATA_FAILURE",
                "CODE_FAILURE", "MODEL_FAILURE", "VALIDATION_FAILURE", "POLICY_FAILURE")),
            "cause_id": nullable(ID), "failure_message": nullable(TEXT),
            "attempt": {"type": "integer", "minimum": 1, "maximum": 3}, "retry_of": nullable(ID),
            "spec": obj({"source_path": PATH, "source_sha256": HASH, "snapshot_path": PATH, "sha256": HASH}),
            "input_manifest_sha256": HASH,
            "inputs": arr(obj({"input_id": ID, "source_path": PATH, "snapshot_path": PATH,
                "sha256": HASH, "size_bytes": {"type": "integer", "minimum": 1}}), 1),
            "code": arr(obj({"source_path": PATH, "snapshot_path": PATH,
                "sha256": HASH, "size_bytes": {"type": "integer", "minimum": 1}}), 1),
            "outputs": arr(obj({"name": ID, "path": PATH, "sha256": HASH,
                "size_bytes": {"type": "integer", "minimum": 1}})),
            "logs": obj({"stdout": obj({"path": PATH, "sha256": HASH, "size_bytes": {"type": "integer", "minimum": 0}}),
                "stderr": obj({"path": PATH, "sha256": HASH, "size_bytes": {"type": "integer", "minimum": 0}})}),
            "control_files": arr(obj({"path": PATH, "sha256": HASH}), 1),
            "contract_snapshots": arr(obj({"contract": enum("validation_criteria", "risk_probe_plan", "method_card", "risk_probe", "run_manifest"),
                "source_path": PATH, "snapshot_path": PATH, "sha256": HASH, "size_bytes": {"type": "integer", "minimum": 1}})),
            "upstream_freezes": arr(obj({"question_id": ID, "freeze_id": ID, "source_path": PATH,
                "snapshot_path": PATH, "sha256": HASH, "size_bytes": {"type": "integer", "minimum": 1}})),
            "scientific_acceptance": {"const": "NOT_RUN"}}, optional=("contract_snapshots", "upstream_freezes")),
        "validation_criteria": contract({"criteria_id": ID, "question_id": ID,
            "task_type": enum("regression", "time_series", "optimization", "mechanism", "graph"),
            "data_input_id": ID, "main_output_name": ID, "baseline_output_name": ID,
            "source_refs": arr(TEXT, 1), "checks": arr(obj({"check_id": ID, "metric": ID,
                "operator": enum("le", "ge", "eq"), "threshold": NUMBER, "unit": TEXT,
                "source_ref": TEXT}), 1),
            "symbol_dimensions": mapping(mapping({"type": "integer"})),
            "robustness": obj({"status": enum("required", "not_applicable"), "reason": TEXT,
                "required_metrics": arr(ID, 0, True)}),
            "evaluation": obj({"sense": enum("min", "max"), "target": nullable(TEXT),
                "bootstrap_repetitions": {"type": "integer", "minimum": 0, "maximum": 10000},
                "confidence": {"type": "number", "exclusiveMinimum": 0, "exclusiveMaximum": 1}})}),
        "validation_summary": contract({"validation_id": ID, "question_id": ID, "actor_id": ID,
            "created_at": TIME, "main_run": obj({"path": PATH, "sha256": HASH}),
            "baseline_run": obj({"path": PATH, "sha256": HASH}),
            "criteria": obj({"path": PATH, "sha256": HASH}),
            "validator_workspace": PATH, "validator_run": obj({"path": PATH, "sha256": HASH}),
            "validator_code": arr(obj({"path": PATH, "sha256": HASH}), 1),
            "measurements": mapping(NUMBER),
            "checks": arr(obj({"check_id": ID, "metric": ID, "value": NUMBER, "operator": enum("le", "ge", "eq"),
                "threshold": NUMBER, "unit": TEXT, "status": enum("PASS", "FAIL")}), 1),
            "status": enum("PASS", "FAIL"), "limitations": arr(TEXT)}),
        "evidence_gate": contract({"evidence_id": ID, "question_id": ID, "created_at": TIME,
            "producer": {"const": "evidence-auditor"}, "validation": obj({"path": PATH, "sha256": HASH}),
            "dependencies": arr(obj({"path": PATH, "sha256": HASH}), 1),
            "status": enum("PASS", "FAIL", "BLOCKED"), "blockers": arr(TEXT),
            "scope": {"const": "computed_model_evidence"}, "official_compliance": {"const": "NOT_RUN"}}),
        "freeze_request": contract({"actor_id": ID, "question_id": ID, "decision_id": ID,
            "numbers": arr(obj({"frozen_number_id": ID, "claim_id": ID, "source_path": PATH,
                "locator": TEXT, "unit": TEXT, "precision": {"type": "integer", "minimum": 0, "maximum": 16}}), 1)}),
        "frozen_numbers": contract({"freeze_id": ID, "version": {"type": "integer", "minimum": 1},
            "question_id": ID, "decision_id": ID, "actor_id": ID, "created_at": TIME,
            "evidence": obj({"path": PATH, "sha256": HASH}),
            "validation": obj({"path": PATH, "sha256": HASH}),
            "main_run": obj({"path": PATH, "sha256": HASH}), "baseline_run": obj({"path": PATH, "sha256": HASH}),
            "numbers": arr(obj({"frozen_number_id": ID, "claim_id": ID, "source_path": PATH,
                "source_sha256": HASH, "locator": TEXT, "value": NUMBER, "unit": TEXT,
                "precision": {"type": "integer", "minimum": 0, "maximum": 16}}), 1),
            "registry_artifact_id": ID}),
        "freeze_event": contract({"event_id": ID, "freeze_id": ID, "kind": enum("FREEZE", "THAW"),
            "actor_id": ID, "timestamp": TIME, "reason": TEXT, "snapshot_path": PATH,
            "snapshot_sha256": HASH, "previous_event_sha256": nullable(HASH)}),
        "freeze_index": contract({"questions": mapping(obj({"freeze_id": ID, "path": PATH, "sha256": HASH,
            "version": {"type": "integer", "minimum": 1}, "status": enum("FROZEN", "THAWED")}))}),
        "agent_task": contract({"task_id": ID, "actor_id": ID, "role": enum("framer", "ambiguity", "data_auditor",
            "method_retriever", "council", "critic", "probe", "decision", "code", "validator", "reviewer", "visual", "writer"),
            "question_id": nullable(ID), "instructions": TEXT, "created_at": TIME,
            "inputs": arr(obj({"artifact_id": ID, "path": PATH, "sha256": HASH}), 1),
            "outputs": arr(obj({"path": PATH, "contract": nullable(TEXT), "format": enum("json", "jsonl", "python", "tex")}), 1),
            "reviewed_actor_id": nullable(ID), "view": nullable(enum("mechanism", "statistics", "optimization", "engineering", "innovation")),
            "interaction_mode": enum("autopilot", "human_gate"),
            "attempt": {"type": "integer", "minimum": 1, "maximum": 3}, "supersedes_task_id": nullable(ID)}),
        "agent_schedule": contract({"case_id": ID,
            "question_dag": nullable(contract({"nodes": arr(obj({"question_id": ID, "depends_on": arr(ID, 0, True)}), 1)})),
            "tasks": arr(obj({"task_id": ID, "actor_id": ID,
                "role": enum("framer", "ambiguity", "data_auditor", "method_retriever", "council", "critic", "probe",
                             "decision", "code", "validator", "reviewer", "visual", "writer"),
                "question_id": nullable(ID), "instructions": TEXT, "inputs": arr(PATH, 1, True),
                "outputs": arr(obj({"path": PATH, "contract": nullable(TEXT), "format": enum("json", "jsonl", "python", "tex")}), 1),
                "reviewed_actor_id": nullable(ID), "view": nullable(enum("mechanism", "statistics", "optimization", "engineering", "innovation")),
                "depends_on": arr(ID, 0, True), "attempt": {"type": "integer", "minimum": 1, "maximum": 3},
                "supersedes_task_id": nullable(ID)}), 1)}),
        "workflow_plan": contract({"case_id": ID, "policy_path": nullable(PATH), "agent_schedule": nullable(PATH),
            "reference_requests": arr(obj({"retrieval_id": ID, "source": TEXT, "question_id": ID,
                "same_problem": BOOL, "baseline_id": nullable(ID)}), 1),
            "framing": obj({name: PATH for name in ("problem_frame", "problem_dag", "symbol_table", "ambiguity_register", "assumption_ledger", "review")}),
            "questions": arr(obj({"question_id": ID, "method_card": PATH, "probe_reports": arr(PATH, 1, True), "probe_specs": arr(PATH, 1, True),
                "decision": PATH, "main_spec": PATH, "baseline_spec": PATH, "code_review": PATH,
                "baseline_code_review": nullable(PATH), "validation_review": PATH,
                "frozen_numbers": arr(obj({"frozen_number_id": ID, "claim_id": ID,
                    "source": enum("validation", "main_output"), "output_name": nullable(ID),
                    "locator": TEXT, "unit": TEXT, "precision": {"type": "integer", "minimum": 0, "maximum": 16}}), 1)},
                optional=("baseline_code_review", "probe_specs")), 1)}, optional=("agent_schedule", "reference_requests")),
        "workflow_progress": contract({"case_id": ID, "questions": mapping(obj({
            "main_run": nullable(PATH), "baseline_run": nullable(PATH), "validation": nullable(PATH), "evidence": nullable(PATH)}))}),
        "agent_response": contract({"task_id": ID, "actor_id": ID, "status": enum("PRODUCED", "BLOCKED"),
            "rationale": TEXT, "evidence_refs": arr(ID), "blockers": arr(TEXT),
            "artifacts": arr(obj({"path": PATH, "content": TEXT}))}),
        "agent_result": contract({"task_id": ID, "actor_id": ID, "role": TEXT, "created_at": TIME,
            "backend": TEXT, "provider": TEXT, "model": nullable(TEXT), "session_id": nullable(TEXT),
            "status": enum("PRODUCED", "BLOCKED", "FAILED"), "request_sha256": HASH,
            "response": nullable(obj({"path": PATH, "sha256": HASH})),
            "artifacts": arr(obj({"artifact_id": ID, "path": PATH, "sha256": HASH})),
            "events": obj({"path": PATH, "sha256": HASH}), "stderr": obj({"path": PATH, "sha256": HASH}),
            "returncode": nullable({"type": "integer"}), "timed_out": BOOL,
            "duration_seconds": {"type": "number", "minimum": 0}, "blockers": arr(TEXT),
            "bundle": arr(obj({"path": PATH, "sha256": HASH}), 1),
            "capabilities": obj({"scoped_input_bundle": BOOL, "validated_output_publication": BOOL,
                "os_read_isolation": BOOL, "reasoning_backend": BOOL})}),
        "semantic_review": contract({"review_id": ID, "actor_id": ID, "reviewed_actor_id": ID,
            "question_id": ID, "artifact_refs": arr(ID, 1, True),
            "findings": arr(obj({"severity": enum("info", "warning", "error"), "issue": TEXT, "evidence_refs": arr(ID, 1)})),
            "verdict": enum("SUPPORTED", "LIMITED", "BLOCKED"), "limitations": arr(TEXT), "created_at": TIME}),
        "method_proposal": contract({"proposal_id": ID, "actor_id": ID, "question_id": ID,
            "view": enum("mechanism", "statistics", "optimization", "engineering", "innovation"),
            "applicable": BOOL, "reason": TEXT, "main_idea": nullable(TEXT), "baseline_idea": nullable(TEXT),
            "assumption_refs": arr(ID), "evidence_refs": arr(ID, 1), "risks": arr(TEXT), "validation_plan": arr(TEXT)}),
        "data_audit": contract({"audit_id": ID, "actor_id": ID, "created_at": TIME,
            "input_manifest_sha256": HASH, "files": arr(obj({"input_id": ID, "sha256": HASH,
                "format": TEXT, "rows": nullable({"type": "integer", "minimum": 0}), "fields": arr(TEXT),
                "missing_values": nullable({"type": "integer", "minimum": 0}),
                "duplicate_rows": nullable({"type": "integer", "minimum": 0}), "observations": arr(TEXT)}), 1),
            "issues": arr(obj({"severity": enum("warning", "error"), "input_id": ID, "message": TEXT})),
            "status": enum("PASS", "WARN", "FAIL")}),
        "method_sources": contract({"actor_id": ID, "question_id": ID, "sources": arr(obj({"source_id": ID,
            "uri": TEXT, "accessed_at": TIME, "snapshot_path": PATH, "sha256": HASH,
            "retrieval": obj({"path": PATH, "sha256": HASH}),
            "same_problem": BOOL, "contribution": TEXT, "limitations": TEXT}, optional=("retrieval",)), 1)}),
        "reference_retrieval": contract({"retrieval_id": ID, "case_id": ID, "question_id": ID,
            "source": TEXT, "same_problem": BOOL, "baseline_id": nullable(ID), "blind_reference_mode": BOOL,
            "started_at": TIME, "finished_at": TIME,
            "timeout_seconds": {"type": "number", "exclusiveMinimum": 0}, "max_bytes": {"type": "integer", "minimum": 1},
            "max_redirects": {"type": "integer", "minimum": 0, "maximum": 10}, "status": enum("RETRIEVED", "FAILED"),
            "failure_type": nullable(TEXT), "snapshot": nullable(obj({"path": PATH, "sha256": HASH,
                "size_bytes": {"type": "integer", "minimum": 1}})),
            "requests": arr(obj({"url": TEXT, "admission_sha256": HASH, "requested_at": TIME,
                "responded_at": nullable(TIME), "status_code": nullable({"type": "integer", "minimum": 100, "maximum": 599}),
                "location": nullable(TEXT), "content_type": nullable(TEXT), "content_encoding": nullable(TEXT),
                "content_length": nullable({"type": "integer", "minimum": 0})})),
            "controls": arr(obj({"path": PATH, "sha256": HASH}), 3),
            "timeout_scope": {"const": "socket_operations_and_between_chunks"},
            "outside_host_blindness": {"const": "UNVERIFIABLE"}}, optional=("blind_reference_mode",)),
        "reference_case_baseline": contract({"baseline_id": ID, "case_id": ID, "created_at": TIME,
            "question_ids": arr(ID, 1, unique=True), "frame_sha256": HASH, "input_manifest_sha256": HASH,
            "baselines": arr(obj({"question_id": ID, "baseline_id": ID, "freeze_id": ID, "path": PATH, "sha256": HASH}), 1),
            "scope": {"const": "host_observed_all_question_pre_reference_baseline"},
            "paper_acceptance": {"const": "NOT_RUN"}}),
        "reference_baseline": contract({"baseline_id": ID, "case_id": ID, "question_id": ID, "freeze_id": ID,
            "created_at": TIME, "framer_task": ID, "writer_task": ID,
            "artifacts": obj({name: arr(obj({"source_path": PATH, "path": PATH, "sha256": HASH}), 1) for name in ("frame", "models", "code", "results", "paper")}),
            "scope": {"const": "host_observed_pre_reference_baseline"}, "paper_acceptance": {"const": "NOT_RUN"}}),
        "recovery_event": contract({"execution_id": ID, "kind": enum("run", "agent"), "status": {"const": "ABANDONED"},
            "recovered_at": TIME, "reason": TEXT, "evidence": arr(obj({"path": PATH, "sha256": HASH}), 2),
            "attempt": {"type": "integer", "minimum": 1, "maximum": 3}, "returncode": {"type": "null"},
            "process_observation": enum("recorded_owner_and_child_stopped", "owner_stopped_execution_not_started"),
            "descendant_quiescence": {"const": "NOT_PROVEN"}, "scientific_acceptance": {"const": "NOT_RUN"}}),
        "risk_probe_plan": contract({"question_id": ID, "method_id": ID, "actor_id": ID,
            "checks": arr(obj({"category": enum("executability", "coverage", "assumptions", "degeneracy", "perturbation", "scale"),
                "not_applicable_reason": nullable(TEXT), "measurements": arr(obj({"metric": ID, "output_name": ID,
                    "locator": TEXT, "operator": enum("le", "ge", "eq"), "threshold": NUMBER})), "reason": TEXT}), 6)}),
    }
